# -*- coding: utf-8 -*-
"""Deblur-GAN_Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17dC05huLxJ4lN-ipsL3qAOQsVD6rAa9u
"""

# 데이터 셋 압축 풀기
import os
import zipfile
import shutil
from google.colab import drive

drive.mount('/content/drive')
local_raw_dir = '/content/ai_hub_raw'
os.makedirs(local_raw_dir, exist_ok=True)

drive_folder = '/content/drive/MyDrive/Colab Notebooks/AI_Hub_Raw'

# 압축 파일 이름 목록 (보내주신 캡처 화면 기준 정확히 매칭)
zip_files = [
    '[원본]원천데이터11.zip',
    '[원본]라벨링데이터.zip',
    '[라벨]자동차번호판...' # 만약 뒷부분 이름이 더 있다면 아래 파일 확인 로직에서 자동 감지하도록 처리하겠습니다.
]

# 드라이브 폴더 내 실제 zip 파일들 탐색
import glob
actual_zips = glob.glob(os.path.join(drive_folder, "*.zip"))

print("📦 1. 구글 드라이브에서 코랩 내부로 데이터셋 복사 중...")
for zip_path in actual_zips:
    file_name = os.path.basename(zip_path)
    target_path = os.path.join(local_raw_dir, file_name)

    print(f"-> {file_name} 복사 중...")
    shutil.copy(zip_path, target_path)

print("\n⚡ 2. 코랩 로컬 영역에서 고속 압축 해제 진행 중...")
extracted_dir = '/content/ai_hub_extracted'
os.makedirs(extracted_dir, exist_ok=True)

for zip_path in glob.glob(os.path.join(local_raw_dir, "*.zip")):
    print(f"-> {os.path.basename(zip_path)} 압축 푸는 중...")
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(extracted_dir)

print("\n🎉 압축 해제 완료! 코랩 로컬 공간에 원본 데이터가 세팅되었습니다.")

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader, random_split
from torchvision import models, transforms
import glob
import os
import random
import cv2
import numpy as np
from PIL import Image, ImageFilter, ImageEnhance

# CCTV 열화 함수 (야간/흔들림/저화질 복합)
def motion_blur_pil(img, kernel_size=9, angle=0):
    arr = np.array(img)
    kernel = np.zeros((kernel_size, kernel_size))
    kernel[kernel_size // 2, :] = np.ones(kernel_size)
    kernel = kernel / kernel_size
    center = (kernel_size / 2 - 0.5, kernel_size / 2 - 0.5)
    rot_mat = cv2.getRotationMatrix2D(center, angle, 1.0)
    kernel = cv2.warpAffine(kernel, rot_mat, (kernel_size, kernel_size))
    blurred = cv2.filter2D(arr, -1, kernel)
    return Image.fromarray(blurred)

def make_perfect_cctv_blur(sharp_img):
    img = sharp_img.copy()
    # 1. 모션 블러
    if random.random() < 0.8:
        k = random.choice([7, 9, 11, 13])
        img = motion_blur_pil(img, kernel_size=k, angle=random.uniform(-15, 15))
    # 2. 저해상도
    if random.random() < 0.8:
        w, h = img.size
        scale = random.uniform(0.3, 0.5)
        img = img.resize((max(16, int(w*scale)), max(8, int(h*scale))), Image.BICUBIC)
        img = img.resize((w, h), Image.NEAREST)
    # 3. 야간 저조도 및 노이즈
    if random.random() < 0.7:
        img = ImageEnhance.Brightness(img).enhance(random.uniform(0.4, 0.7))
        arr = np.array(img).astype(np.float32)
        noise = np.random.normal(0, random.uniform(5, 15), arr.shape)
        img = Image.fromarray(np.clip(arr + noise, 0, 255).astype(np.uint8))
    return img

# 데이터셋 및 모델 정의
class AIHubMasterDataset(Dataset):
    def __init__(self, root_dir, size_w=384, size_h=128):
        self.image_paths = glob.glob(os.path.join(root_dir, "**/*.jpg"), recursive=True) + \
                           glob.glob(os.path.join(root_dir, "**/*.png"), recursive=True)
        self.base_transform = transforms.Compose([transforms.Resize((size_h, size_w), Image.BICUBIC)])
        self.tensor_transform = transforms.Compose([
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.5, 0.5, 0.5], std=[0.5, 0.5, 0.5])
        ])
    def __len__(self): return len(self.image_paths)
    def __getitem__(self, idx):
        sharp_img = Image.open(self.image_paths[idx]).convert('RGB')
        sharp_img = self.base_transform(sharp_img)
        blur_img = make_perfect_cctv_blur(sharp_img)
        return {'blur': self.tensor_transform(blur_img), 'sharp': self.tensor_transform(sharp_img)}

# FPN 정의
class FPNMobileNetGenerator(nn.Module):
    def __init__(self):
        super(FPNMobileNetGenerator, self).__init__()
        backbone = models.mobilenet_v2(weights=models.MobileNet_V2_Weights.DEFAULT).features
        self.enc1, self.enc2, self.enc3, self.enc4 = backbone[0:2], backbone[2:4], backbone[4:7], backbone[7:14]
        self.lateral4, self.lateral3, self.lateral2 = nn.Conv2d(96, 64, 1), nn.Conv2d(32, 64, 1), nn.Conv2d(24, 64, 1)
        self.smooth = nn.Conv2d(64, 64, 3, padding=1)
        self.head = nn.Sequential(nn.Conv2d(64, 32, 3, padding=1), nn.SiLU(), nn.Conv2d(32, 3, 3, padding=1), nn.Tanh())
    def forward(self, x):
        h, w = x.size(2), x.size(3)
        f1 = self.enc1(x); f2 = self.enc2(f1); f3 = self.enc3(f2); f4 = self.enc4(f3)
        p4 = self.lateral4(f4)
        p3 = self.lateral3(f3) + nn.functional.interpolate(p4, size=(f3.size(2), f3.size(3)), mode='nearest')
        p2 = self.lateral2(f2) + nn.functional.interpolate(p3, size=(f2.size(2), f2.size(3)), mode='nearest')
        out = nn.functional.interpolate(self.smooth(p2), size=(h, w), mode='bilinear', align_corners=False)
        return self.head(out)

class DoubleDiscriminator(nn.Module):
    def __init__(self):
        super(DoubleDiscriminator, self).__init__()
        def block(in_c, out_c, stride=2):
            return nn.Sequential(nn.Conv2d(in_c, out_c, 4, stride=stride, padding=1), nn.InstanceNorm2d(out_c), nn.LeakyReLU(0.2, inplace=True))
        self.model = nn.Sequential(block(3, 64, stride=2), block(64, 128, stride=2), block(128, 256, stride=2), block(256, 512, stride=1), nn.Conv2d(512, 1, 4, padding=1))
    def forward(self, x): return self.model(x)

class PerceptualLoss(nn.Module):
    def __init__(self):
        super(PerceptualLoss, self).__init__()
        vgg = models.vgg19(weights=models.VGG19_Weights.DEFAULT).features
        self.loss_network = nn.Sequential(*list(vgg)[:36]).eval()
        for param in self.loss_network.parameters(): param.requires_grad = False
        self.mse = nn.MSELoss()
    def forward(self, fake, real): return self.mse(self.loss_network(fake), self.loss_network(real))

# Deblur-GAN 학습용 코드
def run_final_master_training():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    extracted_dir = '/content/ai_hub_extracted'

    # 🏆 전략 1: 양질의 데이터 3,000장만 샘플링 (속도 핵심)
    full_dataset = AIHubMasterDataset(root_dir=extracted_dir)
    target_size = min(3000, len(full_dataset))
    train_dataset, _ = random_split(full_dataset, [target_size, len(full_dataset) - target_size])
    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True, drop_last=True) # 배치 키움

    netG = FPNMobileNetGenerator().to(device)
    netD = DoubleDiscriminator().to(device)
    criterion_pixel = nn.L1Loss()
    criterion_perceptual = PerceptualLoss().to(device)
    optimizer_G = torch.optim.Adam(netG.parameters(), lr=0.0002, betas=(0.5, 0.999))
    optimizer_D = torch.optim.Adam(netD.parameters(), lr=0.0002, betas=(0.5, 0.999))

    # 🏆 전략 2: 혼합 정밀도 가속기 (AMP)
    scaler = torch.cuda.amp.GradScaler()

    print(f"🚀 [최종 학습 시작] 샘플: {target_size}개 / 목표: 30 Epoch")

    for epoch in range(1, 31):
        netG.train(); netD.train()
        for i, batch in enumerate(train_loader):
            real_blur, real_sharp = batch['blur'].to(device), batch['sharp'].to(device)

            # --- 생성기 학습 ---
            optimizer_G.zero_grad()
            with torch.cuda.amp.autocast():
                fake_sharp = netG(real_blur)
                loss_G = criterion_pixel(fake_sharp, real_sharp) * 30.0 + criterion_perceptual(fake_sharp, real_sharp) * 1.5 + torch.mean((netD(fake_sharp)-1)**2) * 0.001
            scaler.scale(loss_G).backward()
            scaler.step(optimizer_G); scaler.update()

            # --- 판별기 학습 ---
            optimizer_D.zero_grad()
            with torch.cuda.amp.autocast():
                loss_D = (torch.mean((netD(real_sharp)-1)**2) + torch.mean(netD(fake_sharp.detach())**2)) * 0.5
            scaler.scale(loss_D).backward()
            scaler.step(optimizer_D); scaler.update()

        print(f"✅ Epoch [{epoch}/30] 완료")
        if epoch % 5 == 0:
            torch.save(netG.state_dict(), f'/content/drive/MyDrive/Master_Model_Epoch_{epoch}.pth')

if __name__ == "__main__":
    os.makedirs('/content/drive/MyDrive/Master_Model', exist_ok=True)
    run_final_master_training()