# -*- coding: utf-8 -*-
"""최종2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yTUmTq0-yhhpusYaceOMbx5HVhXJpbii

라이브러리 설치
"""

# Commented out IPython magic to ensure Python compatibility.
# 한번만 실행 roboflow yolo install
# %pip install ultralytics supervision roboflow
# prevent ultralytics from tracking your activity
!yolo settings sync=False
import ultralytics
ultralytics.checks()

from google.colab import drive
drive.mount('/content/drive')

"""번호판 크롭"""

import cv2
import os
import shutil
import numpy as np
from ultralytics import YOLO


#yolo 번호판 크롭 모델 불러오기

yolo_model = YOLO("/content/best (1).pt")

video_path = "/content/last.mp4"  #번호판추출할영상경로

output_crop_dir = "/content/cropped_plates_quality_v3"
if os.path.exists(output_crop_dir):
    shutil.rmtree(output_crop_dir)
os.makedirs(output_crop_dir, exist_ok=True)

# 번호판 크롭사이즈및 설정
YOLO_CONF = 0.08
FRAME_STRIDE = 5
MAX_SAVE = 60
MIN_CROP_W = 45
MIN_CROP_H = 15

frame_count = 0
raw_detection_count = 0
candidates = []

print("YOLO크롭성공")
print("video_path exists:", os.path.exists(video_path), video_path)


def expand_box(x1, y1, x2, y2, img_w, img_h, scale_x=1.8, scale_y=1.8):
    bw = x2 - x1
    bh = y2 - y1
    cx = (x1 + x2) / 2
    cy = (y1 + y2) / 2

    new_w = bw * scale_x
    new_h = bh * scale_y

    nx1 = int(max(0, cx - new_w / 2))
    ny1 = int(max(0, cy - new_h / 2))
    nx2 = int(min(img_w, cx + new_w / 2))
    ny2 = int(min(img_h, cy + new_h / 2))

    return nx1, ny1, nx2, ny2


def plate_quality_score(crop, conf):
    if crop is None or crop.size == 0:
        return -999

    gray = cv2.cvtColor(crop, cv2.COLOR_BGR2GRAY)
    h, w = gray.shape[:2]
    area = w * h
    aspect = w / max(1, h)
    sharpness = cv2.Laplacian(gray, cv2.CV_64F).var()
    brightness = gray.mean()
    contrast = gray.std()

    score = 0

   # 번호판 크기별 가산점 점수 부여. 크기가 클수록 좋은 점수.
    if w >= 80 and h >= 25:
        score += 25
    elif w >= 45 and h >= 14:
        score += 10
    else:
        score -= 15

   #가로세로비율(종횡비) 평가
    if 1.4 <= aspect <= 8.5:
        score += 25
    else:
        score -= 10

    #선명도 및 대비 점수 추가
    score += min(sharpness / 5, 45)
    score += min(contrast, 35)


    #밝기 적정성 평가
    if 25 <= brightness <= 235:
        score += 15
    else:
        score -= 10

    #면적이 너무 작은경우 감점
    if area < 500:
        score -= 15

# YOLO 신뢰도 점수 반영
    score += conf * 40
    return score


def add_frame_candidates(frame, frame_id):
    global raw_detection_count

    # imgsz를 크게 설정하여 멀리 있는 작은 번호판도 잘 검출되도록 설정.
    results = yolo_model.predict(source=frame, conf=YOLO_CONF, imgsz=960, verbose=False)

    for r in results:
        for box in r.boxes:
            raw_detection_count += 1
            conf = float(box.conf[0])
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            img_h, img_w = frame.shape[:2]

            x1, y1, x2, y2 = expand_box(
                x1, y1, x2, y2,
                img_w, img_h,
                scale_x=1.8,
                scale_y=1.8,
            )

            crop = frame[y1:y2, x1:x2]
            if crop.size == 0:
                continue

            h, w = crop.shape[:2]
            if w < MIN_CROP_W or h < MIN_CROP_H:
                continue

            score = plate_quality_score(crop, conf)

            # 계산된 score와 함께 후보군에 추가. OCR을 수행할 때 고화질 순으로 처리 가능.
            candidates.append({
                "frame": frame_id,
                "conf": conf,
                "score": score,
                "xyxy": (x1, y1, x2, y2),
                "crop": crop.copy(),
            })


ext = os.path.splitext(video_path)[1].lower()
image_exts = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

if ext in image_exts:
    frame = cv2.imread(video_path)
    assert frame is not None, f"이미지를 읽을 수 없습니다: {video_path}"
    frame_count = 1
    add_frame_candidates(frame, 1)
else:
    cap = cv2.VideoCapture(video_path)
    assert cap.isOpened(), f"영상을 열 수 없습니다. video_path 확인: {video_path}"

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        frame_count += 1
        if frame_count % FRAME_STRIDE != 0:
            continue

        add_frame_candidates(frame, frame_count)

    cap.release()

print("총 처리된 프레임 수:", frame_count)
print("YOLO raw detection 검출 :", raw_detection_count)
print("최종 저장 대상 크롭 이미지 수:", len(candidates))

# 품질 점수를 기준으로 내림차순 정렬. 화질이 가장 좋은 크롭 이미지가 앞으로 오게 됨.
candidates = sorted(candidates, key=lambda x: x["score"], reverse=True)
max_save = min(MAX_SAVE, len(candidates))

for i, item in enumerate(candidates[:max_save], start=1):
    x1, y1, x2, y2 = item["xyxy"]
    crop_name = (
        f"plate_{i:05d}_frame_{item['frame']}_"
        f"score_{item['score']:.1f}_conf_{item['conf']:.2f}_"
        f"box_{x1}_{y1}_{x2}_{y2}.jpg"
    )
    crop_path = os.path.join(output_crop_dir, crop_name)
    cv2.imwrite(crop_path, item["crop"])

print(f"crop이미지 {max_save}개 저장 완 -> {output_crop_dir}")

if max_save == 0:
    print("경고: 크롭된 이미지가 0개입니다. 다음을 확인하세요.")
    print("1) video_path 경로에 실제 파일이 있는지 확인")
    print("2) /content/best (1).pt가 올바른 YOLO 모델 파일인지 확인")
    print("3) YOLO_CONF를 0.01 등으로 낮추어 재시도")

"""DeblurGAN-v2 환경 설정

1 경로 설정

크롭된 번호판 이미지 폴더, Deblur-GAN 가중치 경로, 결과 저장 폴더를 지정하고 파일 존재 여부를 확인합니다.
"""

import os, glob
from pathlib import Path

WEIGHT_PATH = "/content/drive/MyDrive/Colab Notebooks/AI_Hub_Raw/Master_Model_Epoch_15.pth" # 본인 실제 경로 확인
CROP_DIR = "/content/cropped_plates_quality_v3"
OUT_DIR = "/content/deblur_test_results_quality_v3"
ENHANCED_OUT_DIR = "/content/final_plate_enhance_results_quality_v3"

Path(OUT_DIR).mkdir(parents=True, exist_ok=True)
Path(ENHANCED_OUT_DIR).mkdir(parents=True, exist_ok=True)

print("Weight exists:", os.path.exists(WEIGHT_PATH))
print("Crop images:", len(glob.glob(CROP_DIR + "/*")))

assert os.path.exists(WEIGHT_PATH), "가중치 파일 경로가 잘못되었습니다."
assert len(glob.glob(CROP_DIR + "/*")) > 0, "크롭된 번호판 이미지가 없습니다."

"""DeblurGAN 호환 모델 정의"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torchvision import models, transforms
from PIL import Image
import numpy as np
import cv2
import os, glob
from pathlib import Path
import matplotlib.pyplot as plt

class FPNMobileNetGenerator(nn.Module):
    def __init__(self):
        super(FPNMobileNetGenerator, self).__init__()

        # 학습 당시 코드와 동일: torchvision MobileNetV2 backbone 사용
        backbone = models.mobilenet_v2(weights=None).features

        self.enc1 = backbone[0:2]   # 16 channels
        self.enc2 = backbone[2:4]   # 24 channels
        self.enc3 = backbone[4:7]   # 32 channels
        self.enc4 = backbone[7:14]  # 96 channels

        self.lateral4 = nn.Conv2d(96, 64, 1)
        self.lateral3 = nn.Conv2d(32, 64, 1)
        self.lateral2 = nn.Conv2d(24, 64, 1)

        self.smooth = nn.Conv2d(64, 64, 3, padding=1)

        # 학습 당시 AIHub 코드와 동일: SiLU + Tanh
        self.head = nn.Sequential(
            nn.Conv2d(64, 32, 3, padding=1),
            nn.SiLU(inplace=True),
            nn.Conv2d(32, 3, 3, padding=1),
            nn.Tanh()
        )

    def forward(self, x):
        feat1 = self.enc1(x)
        feat2 = self.enc2(feat1)
        feat3 = self.enc3(feat2)
        feat4 = self.enc4(feat3)

        p4 = self.lateral4(feat4)
        p3 = self.lateral3(feat3) + F.interpolate(p4, scale_factor=2, mode="nearest")
        p2 = self.lateral2(feat2) + F.interpolate(p3, scale_factor=2, mode="nearest")

        out = self.smooth(p2)

        # 학습 당시 코드와 동일: scale_factor=4, nearest
        out = F.interpolate(out, scale_factor=4, mode="nearest")

        return self.head(out)

"""DeblurGAN 가중치 로드

저장된 .pth 가중치를 모델에 불러오고, 누락되거나 예상 밖의 파라미터가 있는지 확인합니다.
"""

device = "cuda" if torch.cuda.is_available() else "cpu"

deblur_model = FPNMobileNetGenerator().to(device)

ckpt = torch.load(WEIGHT_PATH, map_location="cpu")
missing, unexpected = deblur_model.load_state_dict(ckpt, strict=False)

deblur_model = deblur_model.to(device).eval()

print("==== Deblur Model Load Result ====")
print("Device:", device)
print("Checkpoint keys:", len(ckpt))
print("Missing keys:", len(missing))
print("Unexpected keys:", len(unexpected))

assert len(missing) == 0, f"Missing keys exist: {missing[:10]}"
assert len(unexpected) == 0, f"Unexpected keys exist: {unexpected[:10]}"

print("학습 당시 Generator 구조로 가중치 로드 성공")

"""학습방식그대로 deblur 추론

크롭된 번호판 이미지를 모델 입력 크기에 맞게 변환한 뒤 Deblur-GAN으로 복원 결과를 생성합니다.
"""

EXACT_OUT_DIR = "/content/deblur_exact_training_model_results"
Path(EXACT_OUT_DIR).mkdir(parents=True, exist_ok=True)

def letterbox_pil(pil_img, size=256, fill=(0, 0, 0)):
    img = pil_img.convert("RGB")
    w, h = img.size

    scale = min(size / w, size / h)
    nw, nh = int(w * scale), int(h * scale)

    resized = img.resize((nw, nh), Image.BICUBIC)
    canvas = Image.new("RGB", (size, size), fill)

    left = (size - nw) // 2
    top = (size - nh) // 2
    canvas.paste(resized, (left, top))

    return canvas

to_tensor_exact = transforms.Compose([
    transforms.Lambda(lambda img: letterbox_pil(img, size=256)),
    transforms.ToTensor(),
    transforms.Normalize([0.5, 0.5, 0.5], [0.5, 0.5, 0.5]),
])

def tensor_to_pil(x):
    x = x.detach().cpu().squeeze(0)
    x = (x * 0.5 + 0.5).clamp(0, 1)
    x = x.permute(1, 2, 0).numpy()
    x = (x * 255).astype(np.uint8)
    return Image.fromarray(x)

image_paths = []
for ext in ["*.jpg", "*.jpeg", "*.png", "*.bmp"]:
    image_paths += glob.glob(os.path.join(CROP_DIR, ext))

image_paths = sorted(image_paths)
print("Track representative images:", len(image_paths))

exact_results = []

deblur_model.eval()

with torch.no_grad():
    for img_path in image_paths:
        original = Image.open(img_path).convert("RGB")

        x = to_tensor_exact(original).unsqueeze(0).to(device)
        y = deblur_model(x)

        restored = tensor_to_pil(y)

        stem = Path(img_path).stem
        save_path = os.path.join(EXACT_OUT_DIR, stem + "_deblur_exact.png")
        restored.save(save_path)

        exact_results.append({
            "original": img_path,
            "deblur_exact": save_path,
        })

print("Deblur exact inference finished:", len(exact_results))
print("Output dir:", EXACT_OUT_DIR)

"""Deblur 결과 + 후처리 후보 생성

원본 crop과 Deblur 결과에 CLAHE, gray 변환, 약한 sharpen 등을 적용해 OCR에 넣을 여러 후보 이미지를 저장
"""

FINAL_OUT_DIR = "/content/final_exact_deblur_candidates_v3"
Path(FINAL_OUT_DIR).mkdir(parents=True, exist_ok=True)

def resize_keep_ratio_for_ocr(pil_img, target_h=128):
    img = pil_img.convert("RGB")
    w, h = img.size

    scale = target_h / h
    new_w = int(w * scale)

    return img.resize((new_w, target_h), Image.BICUBIC)

def clahe_gray_for_ocr(pil_img, clip=1.5):
    img = np.array(pil_img.convert("RGB"))
    gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)

    clahe = cv2.createCLAHE(clipLimit=clip, tileGridSize=(8, 8))
    gray = clahe.apply(gray)

    return Image.fromarray(gray).convert("RGB")

def sharpen_soft(pil_img, amount=1.15, sigma=0.8):
    img = np.array(pil_img.convert("RGB"))
    blur = cv2.GaussianBlur(img, (0, 0), sigma)
    sharp = cv2.addWeighted(img, amount, blur, 1 - amount, 0)
    sharp = np.clip(sharp, 0, 255).astype(np.uint8)

    return Image.fromarray(sharp)

final_results = []

for item in exact_results:
    original_path = item["original"]
    deblur_path = item["deblur_exact"]

    original = Image.open(original_path).convert("RGB")
    deblur = Image.open(deblur_path).convert("RGB")

    # 중요: 정사각형 256 resize 금지. 번호판 비율 유지.
    original_ocr = resize_keep_ratio_for_ocr(original, target_h=128)
    original_gray = clahe_gray_for_ocr(original_ocr, clip=1.5)
    original_gray_sharp = sharpen_soft(original_gray, amount=1.15, sigma=0.8)

    # Deblur 결과는 비교용으로만 저장. OCR 우선순위는 원본 계열.
    deblur_ocr = resize_keep_ratio_for_ocr(deblur, target_h=128)
    deblur_gray = clahe_gray_for_ocr(deblur_ocr, clip=1.5)

    stem = Path(original_path).stem

    original_path_out = os.path.join(FINAL_OUT_DIR, stem + "_00_original_ratio.png")
    original_gray_path = os.path.join(FINAL_OUT_DIR, stem + "_01_original_gray.png")
    original_gray_sharp_path = os.path.join(FINAL_OUT_DIR, stem + "_02_original_gray_sharp.png")
    deblur_path_out = os.path.join(FINAL_OUT_DIR, stem + "_03_deblur_ratio.png")
    deblur_gray_path = os.path.join(FINAL_OUT_DIR, stem + "_04_deblur_gray.png")

    original_ocr.save(original_path_out)
    original_gray.save(original_gray_path)
    original_gray_sharp.save(original_gray_sharp_path)
    deblur_ocr.save(deblur_path_out)
    deblur_gray.save(deblur_gray_path)

    final_results.append({
        "original": original_path_out,
        "original_gray": original_gray_path,
        "original_gray_sharp": original_gray_sharp_path,
        "deblur": deblur_path_out,
        "deblur_gray": deblur_gray_path,
    })

print("Final candidate images:", len(final_results))
print("Output dir:", FINAL_OUT_DIR)

"""결과 시각화

원본, 후처리, Deblur 결과를 나란히 보여주어 OCR 전에 이미지 품질을 눈으로 비교
"""

for r in final_results[:10]:
    imgs = [
        ("original", "Original Ratio"),
        ("original_gray", "Original Gray"),
        ("original_gray_sharp", "Original Gray Sharp"),
        #("deblur", "Deblur Ratio"),
        #("deblur_gray", "Deblur Gray"),
    ]

    plt.figure(figsize=(18, 4))

    for i, (key, title) in enumerate(imgs, start=1):
        img = Image.open(r[key]).convert("RGB")

        plt.subplot(1, len(imgs), i)
        plt.imshow(img)
        plt.title(title)
        plt.axis("off")

    plt.tight_layout()
    plt.show()

"""디블러건 성능평가"""

import os
import glob
import cv2
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PIL import Image

# YOLO가 생성한 기존 번호판 이미지 폴더
TEST_IMAGE_DIR = "/content/cropped_plates_quality_v3"

# 평가 결과 저장 위치
EVAL_RESULT_PATH = "/content/deblurgan_sharpness_results.csv"

# 필요한 변수가 준비됐는지 확인
required_variables = [
    "deblur_model",
    "device",
    "to_tensor_exact"
]

missing_variables = [
    name for name in required_variables
    if name not in globals()
]

if missing_variables:
    raise RuntimeError(
        "먼저 DeblurGAN 모델 로드 셀을 실행하세요. "
        f"없는 변수: {missing_variables}"
    )

def deblur_one_bgr(img_bgr):
    """번호판 이미지를 DeblurGAN으로 복원하고 원래 비율로 변환한다."""

    original_h, original_w = img_bgr.shape[:2]

    rgb = cv2.cvtColor(
        img_bgr,
        cv2.COLOR_BGR2RGB
    )
    pil_img = Image.fromarray(rgb)

    x = (
        to_tensor_exact(pil_img)
        .unsqueeze(0)
        .to(device)
    )

    deblur_model.eval()

    with torch.no_grad():
        y = deblur_model(x)

    y = y.detach().cpu().squeeze(0)
    y = (y * 0.5 + 0.5).clamp(0, 1)
    y = y.permute(1, 2, 0).numpy()

    restored_rgb = (y * 255).astype(np.uint8)

    # 256x256 letterbox에서 실제 번호판 영역만 추출
    scale = min(
        256 / max(original_w, 1),
        256 / max(original_h, 1)
    )

    content_w = max(1, int(original_w * scale))
    content_h = max(1, int(original_h * scale))

    left = (256 - content_w) // 2
    top = (256 - content_h) // 2

    restored_rgb = restored_rgb[
        top:top + content_h,
        left:left + content_w
    ]

    # 원래 번호판 크기로 복원
    restored_rgb = cv2.resize(
        restored_rgb,
        (original_w, original_h),
        interpolation=cv2.INTER_CUBIC
    )

    return cv2.cvtColor(
        restored_rgb,
        cv2.COLOR_RGB2BGR
    )

def laplacian_variance(img):
    """윤곽의 선명도를 라플라시안 분산으로 계산한다."""

    gray = cv2.cvtColor(
        img,
        cv2.COLOR_BGR2GRAY
    )

    return float(
        cv2.Laplacian(
            gray,
            cv2.CV_64F
        ).var()
    )

# 폴더에서 평가 이미지 검색
image_paths = []

for extension in [
    "*.jpg",
    "*.jpeg",
    "*.png",
    "*.bmp"
]:
    image_paths.extend(
        glob.glob(
            os.path.join(
                TEST_IMAGE_DIR,
                extension
            )
        )
    )

image_paths = sorted(image_paths)

print("평가 폴더:", TEST_IMAGE_DIR)
print("발견된 번호판 이미지:", len(image_paths))

if not image_paths:
    raise FileNotFoundError(
        f"평가 이미지가 없습니다: {TEST_IMAGE_DIR}"
    )

rows = []
preview_images = []

for index, image_path in enumerate(image_paths):
    original = cv2.imread(image_path)

    if original is None:
        print("이미지 로드 실패:", image_path)
        continue

    restored = deblur_one_bgr(original)

    before_score = laplacian_variance(original)
    after_score = laplacian_variance(restored)

    change_percent = (
        (after_score - before_score)
        / max(before_score, 1e-9)
        * 100
    )

    rows.append({
        "filename": os.path.basename(image_path),
        "original_sharpness": before_score,
        "deblur_sharpness": after_score,
        "change_percent": change_percent,
        "improved": after_score > before_score
    })

    # 앞의 6장은 비교 시각화용으로 저장
    if len(preview_images) < 6:
        preview_images.append({
            "filename": os.path.basename(image_path),
            "original": original,
            "restored": restored,
            "before": before_score,
            "after": after_score
        })

results = pd.DataFrame(rows)

if results.empty:
    raise RuntimeError(
        "정상적으로 평가된 이미지가 없습니다."
    )

# 전체 성능평가 결과
before_mean = results[
    "original_sharpness"
].mean()

after_mean = results[
    "deblur_sharpness"
].mean()

change_rate = (
    (after_mean - before_mean)
    / max(before_mean, 1e-9)
    * 100
)

improved_count = int(
    results["improved"].sum()
)

improved_rate = (
    results["improved"].mean()
    * 100
)

print("\n" + "=" * 60)
print("DeblurGAN 선명도 성능평가")
print("=" * 60)

print("평가 이미지 수:", len(results))
print(
    "복원 전 평균 선명도:",
    round(before_mean, 2)
)
print(
    "복원 후 평균 선명도:",
    round(after_mean, 2)
)
print(
    "평균 선명도 변화율:",
    round(change_rate, 2),
    "%"
)
print(
    "선명도 향상 이미지:",
    f"{improved_count}/{len(results)}"
)
print(
    "선명도 향상 이미지 비율:",
    round(improved_rate, 2),
    "%"
)

# 상세 결과 저장
results.to_csv(
    EVAL_RESULT_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("평가 결과 저장:", EVAL_RESULT_PATH)

display(results.head(20))

# 원본과 복원 결과 비교
figure, axes = plt.subplots(
    len(preview_images),
    2,
    figsize=(12, 3 * len(preview_images))
)

if len(preview_images) == 1:
    axes = np.array([axes])

for row_index, item in enumerate(preview_images):
    original_rgb = cv2.cvtColor(
        item["original"],
        cv2.COLOR_BGR2RGB
    )

    restored_rgb = cv2.cvtColor(
        item["restored"],
        cv2.COLOR_BGR2RGB
    )

    axes[row_index, 0].imshow(original_rgb)
    axes[row_index, 0].set_title(
        f"Original: {item['before']:.1f}"
    )
    axes[row_index, 0].axis("off")

    axes[row_index, 1].imshow(restored_rgb)
    axes[row_index, 1].set_title(
        f"DeblurGAN: {item['after']:.1f}"
    )
    axes[row_index, 1].axis("off")

plt.tight_layout()
plt.show()

"""PaddleOCR 실행에 필요한 PaddlePaddle GPU 버전을 설치합니다. Colab CUDA 버전에 따라 설치 명령이 달라질 수 있습니다."""

import os

os.environ["FLAGS_use_mkldnn"] = "0"
os.environ["FLAGS_use_onednn"] = "0"
os.environ["PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK"] = "True"

!pip uninstall -y paddlepaddle-gpu paddlepaddle paddleocr paddlex
!pip install -q paddlepaddle==3.0.0 paddleocr pyyaml

print("설치 완료. 이제 런타임을 재시작하세요.")

"""번호판 문자 인식을 위해 PaddleOCR 패키지를 설치"""

# ============================================================
# YAML 설정 파일 파싱을 위한 PyYAML 라이브러리 준비 상태 확인
# - 앞선 단계에서 PaddlePaddle과 함께 설치가 완료된 상태
# - 인공지능 모델의 설정 파일(inference.yml)을 읽어오는 데 사용
# ============================================================

import yaml

# 라이브러리가 정상적으로 불러와졌는지 확인하기 위한 메시지 출력
print("PyYAML 라이브러리 로드 완료 (준비 작동 상태)")

"""OCR에 넣을 후보 이미지 폴더와 결과 저장 폴더를 만들고, 처리할 이미지 개수를 확인"""

import os, glob
from pathlib import Path

ENHANCED_DIR = "/content/final_exact_deblur_candidates_v3"

OCR_OUT_DIR = "/content/ocr_final_results"

Path(OCR_OUT_DIR).mkdir(parents=True, exist_ok=True)

target_images = glob.glob(ENHANCED_DIR + "/*")

print("OCR output directory created:", OCR_OUT_DIR)
print("Images to process for OCR:", len(target_images))

assert len(target_images) > 0, "OCR을 수행할 번호판 이미지가 없습니다. DeblurGAN 단계를 먼저 실행했는지 확인해주세요."

"""이미지를 확대하고 gray/CLAHE 등으로 대비를 조정해 PaddleOCR이 읽기 쉬운 형태로 변환"""

import cv2
import numpy as np

def final_polish_for_ocr(img):
    # 1. 그레이스케일 변환 (흑백 처리의 기본)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    # 2. 대비 향상 (글자를 더 진하게)
    # 픽셀값이 낮은(검은색에 가까운) 부분은 더 어둡게 만듭니다.
    gray = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)[1]

    # 3. 노이즈 제거 (지글지글한 잔상 삭제)
    kernel = np.ones((2, 2), np.uint8)
    processed = cv2.morphologyEx(gray, cv2.MORPH_OPEN, kernel)

    return processed

"""OCR작업

"""

import os
os.environ["FLAGS_use_mkldnn"] = "0"
os.environ["FLAGS_use_onednn"] = "0"
os.environ["PADDLE_PDX_DISABLE_MODEL_SOURCE_CHECK"] = "True"

import glob
import re
from collections import Counter

from paddleocr import PaddleOCR

ocr = PaddleOCR(
    lang="korean",
    use_doc_orientation_classify=False,
    use_doc_unwarping=False,
    use_textline_orientation=False,
)

def polish_for_paddle(img):
    h, w = img.shape[:2]

    if h < 96:
        scale = 96 / h
        img = cv2.resize(img, (int(w * scale), 96), interpolation=cv2.INTER_CUBIC)

    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

    clahe = cv2.createCLAHE(clipLimit=1.8, tileGridSize=(8, 8))
    gray = clahe.apply(gray)

    return cv2.cvtColor(gray, cv2.COLOR_GRAY2BGR)

def extract_texts(result):
    texts = []

    def walk(x):
        if x is None:
            return

        if hasattr(x, "res"):
            walk(x.res)
            return

        if isinstance(x, dict):
            for key in ["rec_texts", "texts", "text"]:
                if key in x:
                    walk(x[key])
            for v in x.values():
                if isinstance(v, (list, tuple, dict)):
                    walk(v)
            return

        if isinstance(x, (list, tuple)):
            if len(x) >= 2 and isinstance(x[1], (list, tuple)) and len(x[1]) >= 1:
                if isinstance(x[1][0], str):
                    texts.append(x[1][0])
                    return

            for item in x:
                walk(item)
            return

        if isinstance(x, str):
            texts.append(x)

    walk(result)
    return " ".join(texts)

def digits_only(text):
    text = (text or "").upper()

    replace_map = {
        "O": "0",
        "Q": "0",
        "D": "0",
        "I": "1",
        "L": "1",
        "|": "1",
        "Z": "2",
        "E": "3",
        "A": "4",
        "S": "5",
        "G": "6",
        "T": "7",
        "B": "8",
    }

    for k, v in replace_map.items():
        text = text.replace(k, v)

    return re.sub(r"[^0-9]", "", text)

target_images = sorted(glob.glob(os.path.join(ENHANCED_DIR, "*")))
print("OCR target images:", len(target_images))

all_rows = []
digit_candidates = []

for img_path in target_images:
    filename = os.path.basename(img_path)
    img = cv2.imread(img_path)

    if img is None:
        continue

    polished = polish_for_paddle(img)

    result = ocr.predict(polished)

    raw_text = extract_texts(result)
    digits = digits_only(raw_text)

    if digits:
        if 3 <= len(digits) <= 8:
            digit_candidates.append(digits)

    all_rows.append({
        "filename": filename,
        "digits": digits,
        "raw": raw_text,
    })

    print(filename, "->", digits, "| raw:", raw_text)

result_path = os.path.join(OCR_OUT_DIR, "paddle_builtin_digit_results.txt")

with open(result_path, "w", encoding="utf-8") as f:
    f.write("filename\tdigits\traw\n")
    for row in all_rows:
        f.write(f"{row['filename']}\t{row['digits']}\t{row['raw']}\n")

counter = Counter(digit_candidates)

print("=" * 70)
print("DIGIT VOTING RESULTS")
for digits, count in counter.most_common(20):
    print(digits, "count=", count)

print("결과 저장:", result_path)

"""시각화"""

import os
import glob
import cv2
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image, ImageDraw, ImageFont

# ============================================================
# FINAL 시각화: 직접 OCR 추론 결과의 최종 시각화 처리
# 앞선 OCR 단계에서 생성된 아래의 파일들을 기반으로 작동합니다:
#   /content/ocr_final_results/best_ocr_results_direct.txt
#   /content/ocr_final_results/total_ocr_results_direct.txt
# ============================================================


# --- 디렉토리 설정 ---
ENHANCED_DIR = "/content/final_exact_deblur_candidates_v3"  # 화질 개선된 입력 이미지 경로
OCR_OUT_DIR = "/content/ocr_final_results"                  # OCR 결과 텍스트 파일 경로
OCR_VARIANT_DIR = os.path.join(OCR_OUT_DIR, "ocr_variants_direct")  # 전처리 방식별 이미지 경로

result_txt_path = os.path.join(OCR_OUT_DIR, "paddle_builtin_digit_results.txt")

print("result exists:", os.path.exists(result_txt_path), result_txt_path)
print("enhanced images:", len(glob.glob(os.path.join(ENHANCED_DIR, "*"))))

rows = []


if os.path.exists(result_txt_path):
    with open(result_txt_path, "r", encoding="utf-8") as f:
        lines = f.readlines()

    for line in lines:
        parts = line.rstrip("\n").split("\t")

        if len(parts) >= 2:
            filename = parts[0]
            digits = parts[1]
            raw = parts[2] if len(parts) >= 3 else ""

            if filename.lower() == "filename":
                continue

            rows.append({
                "plate_id": os.path.splitext(filename)[0],
                "filename": filename,
                "variant": "direct",
                "text": digits,
                "score": "1.0" if digits else "0.0",
                "raw": raw,
            })
else:
    print("오류: OCR 결과 파일이 존재하지 않습니다. 앞의 OCR 단계를 먼저 실행하세요.")
for r in rows:
    score = float(r["score"])
    text = r["text"]

# 시각화용: 점수가 낮아도 일단 상위 결과를 보여줌
rows = [r for r in rows if r["text"]]
rows = sorted(rows, key=lambda r: float(r["score"]), reverse=True)
# --- 최종 시각화 데이터 검증 및 그리기 파트 ---
if not rows:
    print("시각화할 OCR 결과 데이터가 없습니다.")
else:
    print(f"최종 시각화 대상 번호판 수: {len(rows)}")

# 최대 12개의 번호판 이미지만 선택하여 grid 형태로 시각화 화면 구성
    show_count = min(12, len(rows))
    cols = 3 # 가로 3열 배치
    rows_n = int(np.ceil(show_count / cols))  # 필요한 세로 행 개수 계산
    plt.figure(figsize=(18, 5 * rows_n))

    shown = 0

from PIL import ImageFont

font_path = "/usr/share/fonts/truetype/nanum/NanumGothic.ttf"

try:
    font = ImageFont.truetype(font_path, 30)
except Exception:
    font = ImageFont.load_default()

    for item in rows[:show_count]:
        filename = item["filename"]
        stem = os.path.splitext(filename)[0]
        variant = item["variant"]
        text = item["text"]
        score = item["score"]

        # 1순위 이미지 매칭: 실제 문자가 식별된 전처리 변형 이미지 탐색 (파일명에 결과 텍스트가 포함되어 있으므로 와일드카드 사용)
        variant_matches = glob.glob(os.path.join(OCR_VARIANT_DIR, f"{stem}_{variant}_*.png"))
        img_path = variant_matches[0] if variant_matches else ""

        # 2순위 이미지 매칭: 전처리 변형 이미지가 없는 경우 화질 개선된 원본 크롭 이미지로 대체
        if not img_path or not os.path.exists(img_path):
            candidate_path = os.path.join(ENHANCED_DIR, filename)
            if os.path.exists(candidate_path):
                img_path = candidate_path
# 매칭되는 이미지가 디스크에 아예 없는 경우 예외 처리
        if not img_path or not os.path.exists(img_path):
            print(f"이미지를 찾을 수 없어 건너뜁니다: 파일명={filename}, 전처리방식={variant}")
            continue

# 이미지 로드 및 검증
        img = cv2.imread(img_path)
        if img is None:
            print(f"이미지를 읽어오지 못했습니다: {img_path}")
            continue

# OpenCV(BGR)를 Matplotlib/Pillow(RGB) 규격으로 변환
        img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        pil_img = Image.fromarray(img_rgb)
        draw = ImageDraw.Draw(pil_img)

# 이미지 좌측 상단에 번호판 텍스트 정보와 최종 점수를 사각형 박스 위에 오버레이
        label = f"{text}  {score}"
        box_w = min(pil_img.width, max(220, len(label) * 22)) # 라벨 길이에 비례하여 배경 검은색 상자 너비 설정
        draw.rectangle((0, 0, box_w, 42), fill=(0, 0, 0))  # 검은색 배경 상자 그리기
        draw.text((8, 5), label, font=font, fill=(0, 255, 0))  # 형광 연두색 글자 쓰기

        shown += 1
        # Matplotlib 서브플롯 영역에 배치
        plt.subplot(rows_n, cols, shown)
        plt.imshow(np.array(pil_img))
        plt.title(f"{text} / {variant}", fontsize=12)  # 상단에 인식 결과와 사용된 전처리 이름 표시
        plt.axis("off")  # 이미지 테두리의 축 눈금 숨기기


 # 화면에 정상적으로 그려진 이미지가 있는 경우 최종 플롯 출력
    if shown > 0:
        plt.tight_layout()
        plt.show()
    else:
        print("시각화하여 화면에 출력할 유효한 이미지가 발견되지 않았습니다. 위의 파일 경로를 확인하세요.")

"""OCR 성능평가"""

import os
import glob
import re
import cv2
import pandas as pd

TEST_IMAGE_DIR = "/content/cropped_plates_quality_v3"
LABEL_TEMPLATE_PATH = "/content/ocr_evaluation_labels.csv"

if "ocr" not in globals():
    raise RuntimeError(
        "먼저 PaddleOCR 초기화 셀을 실행하세요."
    )

def preprocess_for_ocr(img):
    h, w = img.shape[:2]

    if h < 96:
        scale = 96 / max(h, 1)

        img = cv2.resize(
            img,
            (int(w * scale), 96),
            interpolation=cv2.INTER_CUBIC
        )

    gray = cv2.cvtColor(
        img,
        cv2.COLOR_BGR2GRAY
    )

    clahe = cv2.createCLAHE(
        clipLimit=1.8,
        tileGridSize=(8, 8)
    )

    gray = clahe.apply(gray)

    return cv2.cvtColor(
        gray,
        cv2.COLOR_GRAY2BGR
    )

def extract_texts(result):
    texts = []

    def walk(x):
        if x is None:
            return

        if hasattr(x, "res"):
            walk(x.res)
            return

        if isinstance(x, dict):
            for key in [
                "rec_text",
                "rec_texts",
                "texts",
                "text"
            ]:
                if key in x:
                    walk(x[key])

            for value in x.values():
                if isinstance(
                    value,
                    (dict, list, tuple)
                ):
                    walk(value)

            return

        if isinstance(x, (list, tuple)):
            for value in x:
                walk(value)

            return

        if isinstance(x, str):
            texts.append(x)

    walk(result)

    # 같은 문자열 중복 제거
    unique_texts = []

    for text in texts:
        if text not in unique_texts:
            unique_texts.append(text)

    return " ".join(unique_texts)

def digits_only(text):
    text = (text or "").upper()

    # 비교적 명확한 숫자 혼동만 변환
    replace_map = {
        "O": "0",
        "Q": "0",
        "D": "0",
        "I": "1",
        "L": "1",
        "|": "1",
        "Z": "2",
        "E": "3",
        "S": "5",
        "G": "6",
        "B": "8"
    }

    for before, after in replace_map.items():
        text = text.replace(before, after)

    return re.sub(
        r"[^0-9]",
        "",
        text
    )

image_paths = []

for extension in [
    "*.jpg",
    "*.jpeg",
    "*.png",
    "*.bmp"
]:
    image_paths.extend(
        glob.glob(
            os.path.join(
                TEST_IMAGE_DIR,
                extension
            )
        )
    )

image_paths = sorted(image_paths)

print("평가 폴더:", TEST_IMAGE_DIR)
print("번호판 이미지 수:", len(image_paths))

if not image_paths:
    raise FileNotFoundError(
        f"번호판 이미지가 없습니다: {TEST_IMAGE_DIR}"
    )

rows = []

for index, image_path in enumerate(image_paths):
    img = cv2.imread(image_path)

    if img is None:
        continue

    processed = preprocess_for_ocr(img)
    result = ocr.predict(processed)

    raw_text = extract_texts(result)
    prediction = digits_only(raw_text)

    rows.append({
        "filename": os.path.basename(image_path),
        "prediction": prediction,
        "raw_text": raw_text,

        # 여기에 실제 번호판 숫자를 입력
        "ground_truth": "453652"
    })

    print(
        f"[{index + 1}/{len(image_paths)}]",
        os.path.basename(image_path),
        "->",
        prediction
    )

label_df = pd.DataFrame(rows)

label_df.to_csv(
    LABEL_TEMPLATE_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("\n평가용 CSV 저장 완료:")
print(LABEL_TEMPLATE_PATH)

display(label_df)

import re
import pandas as pd

LABEL_PATH = "/content/ocr_evaluation_labels.csv"
RESULT_PATH = "/content/paddleocr_performance_results.csv"

def clean_digits(value):
    return re.sub(
        r"[^0-9]",
        "",
        str(value)
    )

def edit_distance(a, b):
    a = str(a)
    b = str(b)

    dp = [
        [0] * (len(b) + 1)
        for _ in range(len(a) + 1)
    ]

    for i in range(len(a) + 1):
        dp[i][0] = i

    for j in range(len(b) + 1):
        dp[0][j] = j

    for i in range(1, len(a) + 1):
        for j in range(1, len(b) + 1):
            cost = (
                0
                if a[i - 1] == b[j - 1]
                else 1
            )

            dp[i][j] = min(
                dp[i - 1][j] + 1,
                dp[i][j - 1] + 1,
                dp[i - 1][j - 1] + cost
            )

    return dp[-1][-1]

df = pd.read_csv(
    LABEL_PATH,
    dtype=str
).fillna("")

# 정답이 입력된 행만 평가
df = df[
    df["ground_truth"].str.strip() != ""
].copy()

if df.empty:
    raise RuntimeError(
        "ground_truth 열에 실제 번호판 숫자를 입력하세요."
    )

df["gt_digits"] = (
    df["ground_truth"]
    .apply(clean_digits)
)

df["pred_digits"] = (
    df["prediction"]
    .apply(clean_digits)
)

df["edit_distance"] = df.apply(
    lambda row: edit_distance(
        row["gt_digits"],
        row["pred_digits"]
    ),
    axis=1
)

df["exact_match"] = (
    df["gt_digits"]
    == df["pred_digits"]
)

df["recognized"] = (
    df["pred_digits"].str.len() > 0
)

total_images = len(df)
total_gt_characters = df["gt_digits"].str.len().sum()
total_edit_distance = df["edit_distance"].sum()

cer = (
    total_edit_distance
    / max(total_gt_characters, 1)
)

exact_accuracy = df["exact_match"].mean()
recognition_rate = df["recognized"].mean()

print("=" * 60)
print("PaddleOCR 숫자 인식 성능평가")
print("=" * 60)

print("평가 이미지 수:", total_images)
print("정답 숫자 수:", total_gt_characters)
print("총 편집거리:", total_edit_distance)

print(
    "CER:",
    round(cer * 100, 2),
    "%"
)

print(
    "완전 일치 정확도:",
    round(exact_accuracy * 100, 2),
    "%"
)

print(
    "숫자 검출 성공률:",
    round(recognition_rate * 100, 2),
    "%"
)

df.to_csv(
    RESULT_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("상세 결과 저장:", RESULT_PATH)

display(
    df[
        [
            "filename",
            "gt_digits",
            "pred_digits",
            "edit_distance",
            "exact_match"
        ]
    ]
)