# -*- coding: utf-8 -*-
"""YOLO11_Learning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1be8RpVWEJDBwI7eodtNj2glUhge5ww0K
"""

# Commented out IPython magic to ensure Python compatibility.
# 한번만 실행 roboflow yolo install
# %pip install ultralytics supervision roboflow
!yolo settings sync=False
import ultralytics
ultralytics.checks()

from google.colab import drive
drive.mount('/content/drive')

# roboflow 데이터 받아오는 코드
from google.colab import userdata
from roboflow import Roboflow

# 로보플로우 연결 (본인의 API KEY 입력)
rf = Roboflow(api_key=userdata.get('ROBOFLOW_API_KEY'))
project = rf.workspace("school-2whgn").project("korea-carplate")
version = project.version(1)

# 4. YOLOv8 형식으로 다운로드
dataset = version.download("yolov8")

# Commented out IPython magic to ensure Python compatibility.
# kaggle 데이터 받아오는 코드
import os
from google.colab import userdata

# 1. 환경 변수에 본인의 정보를 입력하세요.
# 발급받은 토큰에 적힌 정보를 그대로 따옴표 안에 넣으시면 됩니다.
os.environ["KAGGLE_USERNAME"] = "skyhole"
os.environ["KAGGLE_KEY"] = userdata.get('KAGGLEAPIKEY')

# 2. kagglehub 설치
# %pip install kagglehub

import kagglehub
import shutil

download_path = kagglehub.dataset_download("zakirkhanaleemi/licence-plates-data")

print("데이터가 다운로드된 위치:", download_path)

target_path = "/content/kaggle_dataset"

if os.path.exists(target_path):
    shutil.rmtree(target_path)

shutil.copytree(download_path, target_path)

print(f"이동 완료! 이제 '{target_path}' 폴더에서 데이터를 확인하세요.")

# 모델 학습용 데이터 통합
# roboflow + kaggle + 직접 찍은 데이터 몇개(증강하여 30개정도)

import os
import shutil
from glob import glob

# 1. 이미지에 표시된 정확한 경로 설정
robo_dir = "/content/Korea-CarPlate-1"
# Kaggle 내부의 실제 YOLO 폴더 (이미지상 깊은 경로 반영)
kaggle_robo_dir = glob("/content/kaggle_dataset/license plate recognition.v2/license plate recognition*")[0]
manual_dir = "/content/kaggle_dataset/extracted_frames"

merged_dir = "/content/merged_dataset"

# [기존 폴더 강제 삭제 후 재생성]
if os.path.exists(merged_dir):
    shutil.rmtree(merged_dir)
    print(f"기존 {merged_dir} 삭제 완료.")

for split in ['train', 'valid']:
    os.makedirs(f"{merged_dir}/{split}/images", exist_ok=True)
    os.makedirs(f"{merged_dir}/{split}/labels", exist_ok=True)

def merge_yolo_folder(src_path, prefix):
    """YOLO 구조의 폴더를 병합하는 함수"""
    count = 0
    for split in ['train', 'valid']:
        img_src = os.path.join(src_path, split, 'images')
        lbl_src = os.path.join(src_path, split, 'labels')

        if not os.path.exists(img_src): continue

        for img_file in os.listdir(img_src):
            base_name = os.path.splitext(img_file)[0]
            # 이미지 복사
            shutil.copy(f"{img_src}/{img_file}", f"{merged_dir}/{split}/images/{prefix}_{img_file}")

            # 라벨 복사 및 클래스 ID 0번 고정
            txt_src = f"{lbl_src}/{base_name}.txt"
            if os.path.exists(txt_src):
                with open(txt_src, 'r') as fin, open(f"{merged_dir}/{split}/labels/{prefix}_{base_name}.txt", 'w') as fout:
                    for line in fin:
                        parts = line.strip().split()
                        if len(parts) >= 5:
                            parts[0] = '0' # 무조건 번호판(0)으로 통일
                            fout.write(" ".join(parts) + "\n")
            count += 1
    return count

print(" 데이터 통합 병합 프로세스 시작...")

# 2. Roboflow(Korea-CarPlate-1) 병합
c1 = merge_yolo_folder(robo_dir, "robo1")
print(f"✅ Korea-CarPlate-1 데이터 {c1}장 완료")

# 3. Kaggle 내부 YOLO 데이터 병합
c2 = merge_yolo_folder(kaggle_robo_dir, "kaggle")
print(f"✅ Kaggle YOLO 데이터 {c2}장 완료")

# 4. 직접 라벨링한 데이터(extracted_frames) 병합 - 모두 train에 넣기
m_imgs = glob(f"{manual_dir}/*.[jJ][pP]*[gG]") + glob(f"{manual_dir}/*.png")
m_count = 0
for img_path in m_imgs:
    f_name = os.path.basename(img_path)
    b_name = os.path.splitext(f_name)[0]
    t_path = f"{manual_dir}/{b_name}.txt"
    if os.path.exists(t_path):
        shutil.copy(img_path, f"{merged_dir}/train/images/manual_{f_name}")
        with open(t_path, 'r') as fin, open(f"{merged_dir}/train/labels/manual_{b_name}.txt", 'w') as fout:
            for line in fin:
                parts = line.strip().split()
                if len(parts) >= 5:
                    parts[0] = '0'
                    fout.write(" ".join(parts) + "\n")
        m_count += 1
print(f"✅ 직접 라벨링 데이터 {m_count}장 완료")

# 5. YAML 생성
yaml_content = f"train: {merged_dir}/train/images\nval: {merged_dir}/valid/images\nnc: 1\nnames: ['license-plate']"
with open(f"{merged_dir}/data.yaml", "w") as f: f.write(yaml_content)

print("-" * 30)
print(f"🎉 최종 병합 완료! [총 학습 데이터: {len(os.listdir(merged_dir+'/train/images'))}장]")

# 모델 학습
#----------------------------------------필요한 경우에만 실행할 것--------------------------------------------
from ultralytics import YOLO

# yolo11n 모델로 100번 반복 학습 640 사이즈(혹시나 실행할까봐 1로 설정)
# epochs 숫자로 반복 횟수 지정
# 번호판만 추출함

model = YOLO("yolo11n.pt")
# results = model.train(data="/content/merged_dataset/data.yaml", epochs=100, imgsz=640)

# 10번 학습할 때마다 체크포인트 가중치를 저장
results = model.train(
    data="/content/merged_dataset/data.yaml",
    epochs=100,
    imgsz=640,
    save_period=10
)

# 1. runs 폴더 전체를 'yolo11_results.zip'이라는 이름으로 압축
!zip -r /content/yolo11_results.zip /content/runs

# 2. 압축된 파일을 내 컴퓨터(로컬)로 다운로드
from google.colab import files
files.download('/content/yolo11_results.zip')

from ultralytics import YOLO
from roboflow import Roboflow

# 이미지 테스트
model = YOLO("/content/best.pt")
results = model.predict(source="/content/car_test3.jpg", conf=0.25, save=True)

# 결과물 시각화
from PIL import Image
for r in results:
    im_array = r.plot()
    im = Image.fromarray(im_array[..., ::-1])
    display(im)

# 영상 테스트
model.predict(source="/content/Video Project 5.mp4", save=True)

# YOLO11 지표 출력
from ultralytics import YOLO

# 1. 복사한 내 가중치 파일 경로 넣기
model = YOLO('/content/drive/MyDrive/test_YOLO11/YOLO11_weight.pt')

# 2. dataset.yaml로 검증 실행
results = model.val(data='/content/merged_dataset/data.yaml')

# 3. 주요 지표 깔끔하게 출력
print("\n" + "="*50)
print(f"종합 인식률 (mAP50-95): {results.box.map:.4f}")
print(f"정밀도 (Precision): {results.box.mp:.4f}")
print(f"재현율 (Recall): {results.box.mr:.4f}")
print("="*50)